config/routes.rb
Rails.application.routes.draw do
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'location' => 'static_pages#location'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <!--  <link href="assets/css/bootstrap-responsive.css" rel="stylesheet"> -->
    <title><%= full_title('Red Bank Lazer Treaments') %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "better-simple-slideshow" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.railstutorial.org/">Developed</a>
    by <a href="http://www.michaelhartl.com/">Christopher Mancuso</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <%= link_to "Red Bank Laser Treatments", root_path, id: "logo", :class => "fancy" %>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Location & Hours", location_path %></li>
        <li><%= link_to "About Us", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%'Red Bank Lazer Treaments'%></title>
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">

    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>
<div class = "container" style ="font-size: 22px; font-family: Calibri">
	<div class = "col-md-2" style =" float:left; margin-right: 10px">
  		<%= image_tag("Dr_David_Hyppolite.jpg")%>
  	</div>
  	<div class ="col-md-9">
  			 <i>Doctor Hyppolite has been providing laser hair treatment to the Red Bank Community for over 30 years. In that time, he has allowed hundreds of patients to realize their dream bodies. He graduated from [INSERT SCHOOL] in [YEAR] and has been recommended time and time again by his patients.</i>
  	</div>
</div>
<footer class ="footer"></footer>

<div class = "container"style ="font-size: 22px; font-family: Calibri">
	
  	<div class = "col-md-2" style ="font-size: 40px; float: right; margin-left: 10px">
  		<%= image_tag("Dr_David_Hyppolite.jpg")%>

  	</div>
  	<div class = "col-md-9">
  			 <i>Doctor Hyppolite has been providing laser hair treatment to the Red Bank Community for over 30 years. In that time, he has allowed hundreds of patients to realize their dream bodies. He graduated from [INSERT SCHOOL] in [YEAR] and has been recommended time and time again by his patients.</i>
 	</div>
</div>

</p>

app/views/static_pages/contact.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="well well-sm">
                <form class="form-horizontal" method="post">
                    <fieldset>
                        <legend class="text-center header">Contact us</legend>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-user bigicon"></i></span>
                            <div class="col-md-8">
                                <input id="fname" name="name" type="text" placeholder="First Name" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-user bigicon"></i></span>
                            <div class="col-md-8">
                                <input id="lname" name="name" type="text" placeholder="Last Name" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-envelope-o bigicon"></i></span>
                            <div class="col-md-8">
                                <input id="email" name="email" type="text" placeholder="Email Address" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-phone-square bigicon"></i></span>
                            <div class="col-md-8">
                                <input id="phone" name="phone" type="text" placeholder="Phone" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-pencil-square-o bigicon"></i></span>
                            <div class="col-md-8">
                                <textarea class="form-control" id="message" name="message" placeholder="Enter your massage for us here. We will get back to you within 2 business days." rows="7"></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>

<style>
    .header {
        color: #36A0FF;
        font-size: 27px;
        padding: 10px;
    }

    .bigicon {
        font-size: 35px;
        color: #36A0FF;
    }
</style>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div>
  <h1>Welcome to the Red Bank Hair Removal Care Center</h1>

  <h2>
    Doctor David Hypoppolite and team have specialized for over 10 years in expert hair removal
  </h2>

<!-- Place in the <head>, after the three links -->
  <script type="text/javascript" charset="utf-8">
    window.onload=function() {
      $('.flexslider').flexslider({
        animation: "slide"
      });
    };
  </script>
</div>
<div class="flexslider">
  <ul class="slides">
    <li>
        <%= image_tag("hair-removal.jpg", width: "100%", height: "400px", :align=> "middle")%>     
    </li>
    <li>
        <%= image_tag("lazer hair.jpg", width: "100%", height: "400px", :align=> "middle")%>   
    </li>
  </ul>
</div>

app/views/static_pages/location.html.erb
<h1>Location and Hours</h1>
  <div class = "col-md-6" style = "text-align:center">
    <h3 style = "text-align:center">Office Address<a href = "https://www.google.com/maps/place/Providential+Medical+Center/@40.3482884,-74.0774702,17z/data=!4m13!1m7!3m6!1s0x89c23034e97bfee5:0xd83edbac4c213150!2s66+Bridge+Ave,+Red+Bank,+NJ+07701!3b1!8m2!3d40.3482843!4d-74.0752815!3m4!1s0x89c23034e97bfee5:0x97e74ac02b517bd!8m2!3d40.348302!4d-74.075208" style ="text-align: center"></h3><h2><br>66 Bridge Ave, <br> Red Bank, NJ 07701</a></h2>
</div>
<div class = "col-md-6" style = "text-align:center">
    <h3>Office Hours</h3>
    <h2>
    Monday:  10AM–4:30PM<br>
    Tuesday: 10AM–6:30PM<br>
    Wednesday: Closed<br>
    Thursday:  10AM–4:30PM<br>
    </h2>
</div>
<%= image_tag("Location.png", width: "100%", :align=> "middle")%> 
<p>


</p>